name: Run test cases

on:
  push:
  pull_request:

jobs:
  run_test_cases:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 24.3.4
    steps:
      - name: install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: 3.20.0
      - name: xref
        run: make xref
      - name: dialyzer
        run: make dialyzer
      - name: eunit
        run: make eunit
